### ISSUE TITLE
A security vulnerability submission

### ISSUE THREAD

**Issue by Al1ex** [Bixbcoin/BIXBcoin-core#1]
Hello, I found a vulnerability which can cause double spend attack. I want to know how to submit vulnerability details and vulnerability reward rules. You can contact me via TG(@RedTeamPing).

**Comment by asma-khordsal** [comment]
> سلام ، من یک آسیب پذیری پیدا کردم که می تواند باعث حمله مضاعف شود. من می خواهم بدانم که چگونه جزئیات آسیب پذیری و قوانین پاداش آسیب پذیری را ارائه دهم. می توانید از طریق TG (RedTeamPing @) با من تماس بگیرید.

09305475510

**Comment by asma-khordsal** [comment]
۰۹۳۰۵۴۷۵۵۱۰

**Comment by Bixbcoin** [comment]
Hi @Al1ex, thanks for report, please send the details to support@bixbcoin.com.

**Comment by Al1ex** [comment]
Okay.

**Comment by Al1ex** [comment]
Okay.

**Comment by Al1ex** [comment]
Hello, I'd like to know your current review progress on this vulnerability. We look forward to your feedback on this vulnerability.
